# main.py
import random
from fetchers.youtube_fetcher import search_youtube_short_videos
from downloaders.downloader import download_with_ytdlp
from editor import compose_short
from uploader import upload_video

from config import MIN_CLIPS, MAX_CLIPS

def main():
    print("🔍 Searching YouTube for trending funny/viral shorts...")
    # Fetch curated videos from YouTube only
    yt_videos = search_youtube_short_videos(
        tags=("short", "funny", "viral"),
        max_results=50,
        max_total_duration=58,
        min_clips=MIN_CLIPS,
        max_clips=MAX_CLIPS,
    )

    if not yt_videos:
        print("❌ No suitable YouTube shorts found. Exiting.")
        return

    print(f"✅ Found {len(yt_videos)} clips within duration limit.")
    for i, v in enumerate(yt_videos, start=1):
        print(f"   {i}. {v['title']} ({v['duration']}s)")

    # 2️⃣ Download the selected clips
    downloaded_paths = []
    for i, vid in enumerate(yt_videos):
        try:
            print(f"⬇️  Downloading clip {i + 1}/{len(yt_videos)}: {vid['title']}")
            path = download_with_ytdlp(vid["url"], filename_prefix=f"clip{i}")
            downloaded_paths.append(path)
        except Exception as e:
            print(f"⚠️  Failed to download {vid.get('url')}: {e}")

    if not downloaded_paths:
        print("❌ No clips were successfully downloaded.")
        return

    # 3️⃣ Compose into one vertical short (labels now auto-generated in editor.py)
    print("🎬 Editing and compiling video...")
    output_path = compose_short(downloaded_paths, output_filename="final_short.mp4")
    print(f"✅ Final short created at: {output_path}")

    # 4️⃣ Use the funny title generated by editor.py
    title = getattr(output_path, "ai_generated_title", None)
    if not title:
        title = "Funny Compilation Shorts 😂"
    print(f"📝 Using AI-generated title: {title}")

    # 5️⃣ Upload to YouTube
    print("📤 Uploading to YouTube...")

    try:
        response = upload_video(
            file_path=output_path,
            title=title,
            description="Compilation of trending funny and viral shorts automatically created by the bot.",
            tags=["shorts", "funny", "viral", "compilation", "trending"],
            privacy="public"
        )
        print("✅ Upload completed successfully!")
        print(f"🎬 Video URL: https://www.youtube.com/watch?v={response.get('id', 'UNKNOWN')}")
    except Exception as e:
        print(f"❌ Upload failed: {e}")

if __name__ == "__main__":
    main()